<?php
require("../../inc/header.php");

/*
		SoftName : EmpireBak Version 2010
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

E_D("DROP TABLE IF EXISTS `ty_store_msg_tpl`;");
E_C("CREATE TABLE `ty_store_msg_tpl` (
  `smt_code` varchar(100) NOT NULL COMMENT '模板编码',
  `smt_name` varchar(100) NOT NULL COMMENT '模板名称',
  `smt_message_switch` tinyint(3) unsigned NOT NULL COMMENT '站内信默认开关，0关，1开',
  `smt_message_content` varchar(255) NOT NULL COMMENT '站内信内容',
  `smt_message_forced` tinyint(3) unsigned NOT NULL COMMENT '站内信强制接收，0否，1是',
  `smt_short_switch` tinyint(3) unsigned NOT NULL COMMENT '短信默认开关，0关，1开',
  `smt_short_content` varchar(255) NOT NULL COMMENT '短信内容',
  `smt_short_forced` tinyint(3) unsigned NOT NULL COMMENT '短信强制接收，0否，1是',
  `smt_mail_switch` tinyint(3) unsigned NOT NULL COMMENT '邮件默认开，0关，1开',
  `smt_mail_subject` varchar(255) NOT NULL COMMENT '邮件标题',
  `smt_mail_content` text NOT NULL COMMENT '邮件内容',
  `smt_mail_forced` tinyint(3) unsigned NOT NULL COMMENT '邮件强制接收，0否，1是',
  PRIMARY KEY (`smt_code`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='商家消息模板'");
E_D("replace into `ty_store_msg_tpl` values('complain','商品被投诉提醒','1','您售出的商品被投诉，等待商家申诉。投诉单编号：{\$complain_id}。','1','0','【{\$site_name}】您售出的商品被投诉，等待商家申诉。投诉单编号：{\$complain_id}。','0','0','{\$site_name}提醒：您售出的商品被投诉，等待商家申诉。投诉单编号：{\$complain_id}。','<p>\r\n	{\$site_name}提醒：\r\n</p>\r\n<p>\r\n	您售出的商品被投诉，等待商家申诉。投诉单编号：{\$complain_id}。\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$site_name}\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$mail_send_time}\r\n</p>\r\n<p>\r\n	<br />\r\n</p>','0');");
E_D("replace into `ty_store_msg_tpl` values('goods_storage_alarm','商品库存预警','1','您的商品库存不足，请及时补货。平台货号：{\$common_id}，SKU：{\$sku_id}。','1','0','【{\$site_name}】您的商品库存不足，请及时补货。平台货号：{\$common_id}，SKU：{\$sku_id}。','0','0','{\$site_name}提醒：您的商品库存不足，请及时补货。','<p>\r\n	{\$site_name}提醒：\r\n</p>\r\n<p>\r\n	您的商品库存不足，请及时补货。平台货号：{\$common_id}，SKU：{\$sku_id}。\r\n</p>\r\n<p>\r\n	点击下面链接查看商品详细信息\r\n</p>\r\n<p>\r\n	<a href=\"http://{\$shop_site_url}/index.php?act=goods&amp;op=index&amp;goods_id={\$sku_id}\" target=\"_blank\">http://{\$shop_site_url}/index.php?act=goods&amp;op=index&amp;goods_id={\$sku_id}</a> \r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$site_name}\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$mail_send_time}\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<br />','0');");
E_D("replace into `ty_store_msg_tpl` values('goods_verify','商品审核失败提醒','1','您的商品没有通过管理员审核，原因：“{\$remark}”。平台货号：{\$common_id}。','1','0','【{\$site_name}】您的商品没有通过管理员审核，原因：“{\$remark}”。平台货号：{\$common_id}。','0','0','{\$site_name}提醒：您的商品没有通过管理员审核。','<p>\r\n	{\$site_name}提醒：\r\n</p>\r\n<p>\r\n	您的商品没有通过管理员审核，原因：“{\$remark}”。平台货号：{\$common_id}。\r\n	</p><p>\r\n		<br />\r\n	</p>\r\n	<p>\r\n		<br />\r\n	</p>\r\n	<p style=\"text-align:right;\">\r\n		{\$site_name}\r\n	</p>\r\n	<p style=\"text-align:right;\">\r\n		{\$mail_send_time}\r\n	</p>','0');");
E_D("replace into `ty_store_msg_tpl` values('goods_violation','商品违规被下架','1','您的商品被违规下架，原因：“{\$remark}”。平台货号：{\$common_id}。','1','0','【{\$site_name}】您的商品被违规下架，原因：“{\$remark}”。平台货号：{\$common_id}。','0','0','{\$site_name}提醒：您的商品被违规下架。','<p>\r\n	{\$site_name}提醒：\r\n</p>\r\n<p>\r\n	您的商品被违规下架。，原因：“{\$remark}”。平台货号：{\$common_id}。\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$site_name}\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$mail_send_time}\r\n</p>\r\n<p>\r\n	<br />\r\n</p>','0');");
E_D("replace into `ty_store_msg_tpl` values('new_order','新订单提醒','1','您有订单需要处理，订单编号：{\$order_sn}。','1','0','【{\$site_name}】您有订单需要处理，订单编号：{\$order_sn}。','0','0','{\$site_name}提醒：您有订单需要处理。','<p>\r\n	{\$site_name}提醒：\r\n</p>\r\n<p>\r\n	您有订单需要处理，订单编号：{\$order_sn}。\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$site_name}\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$mail_send_time}\r\n</p>\r\n<br />','0');");
E_D("replace into `ty_store_msg_tpl` values('refund','退款提醒','1','您有一个{\$type}退款单需要处理，退款编号：{\$refund_sn}。','1','0','【{\$site_name}】您有一个{\$type}退款单需要处理，退款编号：{\$refund_sn}。','1','0','{\$site_name}提醒：您有一个{\$type}退款单需要处理，退款编号：{\$refund_sn}。','<p>\r\n	{\$site_name}提醒：\r\n</p>\r\n<p>\r\n	您有一个{\$type}退款单需要处理，退款编号：{\$refund_sn}。\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$site_name}\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$mail_send_time}\r\n</p>\r\n<p>\r\n	<br />\r\n</p>','1');");
E_D("replace into `ty_store_msg_tpl` values('refund_auto_process','退款自动处理提醒','1','您的{\$type}退款单超期未处理，已自动同意买家退款申请。退款单编号：{\$refund_sn}。','1','0','【{\$site_name}】您的{\$type}退款单超期未处理，已自动同意买家退款申请。退款单编号：{\$refund_sn}。','0','0','{site_name}提醒：您的{\$type}退款单超期未处理，已自动同意买家退款申请。退款单编号：{\$refund_sn}。','<p>\r\n	{site_name}提醒：\r\n</p>\r\n<p>\r\n	您的{\$type}退款单超期未处理，已自动同意买家退款申请。退款单编号：{\$refund_sn}。\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$site_name}\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$mail_send_time}\r\n</p>\r\n<p>\r\n	<br />\r\n</p>','0');");
E_D("replace into `ty_store_msg_tpl` values('return','退货提醒','1','您有一个{\$type}退货单需要处理。退货编号：{\$refund_sn}。','1','0','【{site_name}】您有一个{\$type}退货单需要处理。退货编号：{\$refund_sn}。','0','0','{\$site_name}提醒：您有一个{\$type}退货单需要处理。退货编号：{\$refund_sn}。','<p>\r\n	{\$site_name}提醒：\r\n</p>\r\n<p>\r\n	您有一个{\$type}退货单需要处理。退货编号：{\$refund_sn}。\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$site_name}\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$mail_send_time}\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<br />','0');");
E_D("replace into `ty_store_msg_tpl` values('return_auto_process','退货自动处理提醒','1','您的{\$type}退货单超期未处理，已自动同意买家退货申请（弃货）。退货单编号：{\$refund_sn}。','1','0','【{\$site_name}】您的{\$type}退货单超期未处理，已自动同意买家退货申请（弃货）。退货单编号：{\$refund_sn}。','0','0','{\$site_name}提醒：您的{\$type}退货单超期未处理，已自动同意买家退货申请（弃货）。退货单编号：{\$refund_sn}。','<p>\r\n	{\$site_name}提醒：\r\n</p>\r\n<p>\r\n	您的{\$type}退货单超期未处理，已自动同意买家退货申请（弃货）。退货单编号：{\$refund_sn}。\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$site_name}\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$mail_send_time}\r\n</p>','0');");
E_D("replace into `ty_store_msg_tpl` values('return_auto_receipt','退货未收货自动处理提醒','1','您的{\$type}退货单不处理收货超期未处理，已自动按弃货处理。退货单编号：{\$refund_sn}。','1','0','【{\$site_name}】您的{\$type}退货单不处理收货超期未处理，已自动按弃货处理。退货单编号：{\$refund_sn}。','0','0','{\$site_name}提醒：您的{\$type}退货单超期未处理，已自动同意买家退货申请（弃货）。退货单编号：{\$refund_sn}。','<p>\r\n	{\$site_name}提醒：\r\n</p>\r\n<p>\r\n	您的{\$type}退货单超期未处理，已自动同意买家退货申请（弃货）。退货单编号：{\$refund_sn}。\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$site_name}\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$mail_send_time}\r\n</p>\r\n<p>\r\n	<br />\r\n</p>','0');");
E_D("replace into `ty_store_msg_tpl` values('store_bill_affirm','结算单等待确认提醒','1','您有新的结算单等待确认，开始时间：{\$state_time}，结束时间：{\$end_time}，结算单号：{\$bill_no}。','1','0','【{\$site_name}】您有新的结算单等待确认，开始时间：{\$state_time}，结束时间：{\$end_time}，结算单号：{\$bill_no}。','0','0','{\$site_name}提醒：您有新的结算单等待确认。','<p>\r\n	{\$site_name}提醒：\r\n</p>\r\n<p>\r\n	您有新的结算单等待确认，起止时间：开始时间：{\$state_time}，结束时间：{\$end_time}，结算单号：{\$bill_no}。\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$site_name}\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$mail_send_time}\r\n</p>\r\n<p>\r\n	<br />\r\n</p>','0');");
E_D("replace into `ty_store_msg_tpl` values('store_bill_gathering','结算单已经付款提醒','1','您的结算单平台已付款，请注意查收，结算单编号：{\$bill_no}。','1','0','【{\$site_name}】您的结算单平台已付款，请注意查收，结算单编号：{\$bill_no}。','0','0','{\$site_name}提醒：您的结算单平台已付款，请注意查收。','<p>\r\n	</p><p>\r\n		{\$site_name}提醒：\r\n	</p>\r\n\r\n<p>\r\n	您的结算单平台已付款，请注意查收，结算单编号：{\$bill_no}。\r\n	</p><p>\r\n		<br />\r\n	</p>\r\n	<p>\r\n		<br />\r\n	</p>\r\n	<p>\r\n		<br />\r\n	</p>\r\n	<p style=\"text-align:right;\">\r\n		{\$site_name}\r\n	</p>\r\n	<p style=\"text-align:right;\">\r\n		{\$mail_send_time}\r\n	</p>\r\n\r\n<br />','0');");
E_D("replace into `ty_store_msg_tpl` values('store_cost','店铺消费提醒','1','您有一条新的店铺消费记录，金额：{\$price}，操作人：{\$seller_name}，备注：{\$remark}。','1','0','【{\$site_name}】您有一条新的店铺消费记录，金额：{\$price}，操作人：{\$seller_name}，备注：{\$remark}。','0','0','{\$site_name}提醒：您有一条新的店铺消费记录。','<p>\r\n	{\$site_name}提醒：\r\n</p>\r\n<p>\r\n	您有一条新的店铺消费记录，金额：{\$price}，操作人：{\$seller_name}，备注：{\$remark}。\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$site_name}\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$mail_send_time}\r\n</p>','0');");
E_D("replace into `ty_store_msg_tpl` values('store_expire','店铺到期提醒','1','你的店铺即将到期，请及时续期。','1','0','【{\$site_name}】你的店铺即将到期，请及时续期。','0','0','{\$site_name}提醒：你的店铺即将到期，请及时续期。','<p>\r\n	{\$site_name}提醒：\r\n</p>\r\n<p>\r\n	你的店铺即将到期，请及时续期。\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$site_name}\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$mail_send_time}\r\n</p>\r\n<p>\r\n	<br />\r\n</p>','0');");

require("../../inc/footer.php");
?>