<?php
require("../../inc/header.php");

/*
		SoftName : EmpireBak Version 2010
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

E_D("DROP TABLE IF EXISTS `ty_member_msg_tpl`;");
E_C("CREATE TABLE `ty_member_msg_tpl` (
  `mmt_code` varchar(50) NOT NULL COMMENT '用户消息模板编号',
  `mmt_name` varchar(50) NOT NULL COMMENT '模板名称',
  `mmt_message_switch` tinyint(3) unsigned NOT NULL COMMENT '站内信接收开关',
  `mmt_message_content` varchar(255) NOT NULL COMMENT '站内信消息内容',
  `mmt_short_switch` tinyint(3) unsigned NOT NULL COMMENT '短信接收开关',
  `mmt_short_content` varchar(255) NOT NULL COMMENT '短信接收内容',
  `mmt_mail_switch` tinyint(3) unsigned NOT NULL COMMENT '邮件接收开关',
  `mmt_mail_subject` varchar(255) NOT NULL COMMENT '邮件标题',
  `mmt_mail_content` text NOT NULL COMMENT '邮件内容',
  PRIMARY KEY (`mmt_code`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='用户消息模板'");
E_D("replace into `ty_member_msg_tpl` values('arrival_notice','到货通知提醒','1','您关注的商品 “{\$goods_name}” 已经到货。<a href=\"{\$goods_url}\" target=\"_blank\">点击查看商品</a>','0','【{\$site_name}】您关注的商品 “{\$goods_name}” 已经到货。','0','{\$site_name}提醒：您关注的商品  “{\$goods_name}” 已经到货。','<p>\r\n	{\$site_name}提醒：\r\n</p>\r\n<p>\r\n	您关注的商品 “{\$goods_name}” 已经到货。\r\n</p>\r\n<p>\r\n	<a href=\"{\$goods_url}\" target=\"_blank\">点击查看商品</a> \r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$site_name}\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$mail_send_time}\r\n</p>');");
E_D("replace into `ty_member_msg_tpl` values('consult_goods_reply','商品咨询回复提醒','1','您关于商品 “{\$goods_name}”的咨询，商家已经回复。<a href=\"{\$consult_url}\" target=\"_blank\">点击查看回复</a>','0','【{\$site_name}】您关于商品 “{\$goods_name}” 的咨询，商家已经回复。','0','{\$site_name}提醒：您关于商品 “{\$goods_name}”的咨询，商家已经回复。','<p>\r\n	{\$site_name}提醒：\r\n</p>\r\n<p>\r\n	您关注的商品“{\$goods_name}” 已经到货。\r\n</p>\r\n<p>\r\n	<a href=\"{\$consult_url}\" target=\"_blank\">点击查看回复</a> \r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$site_name}\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$mail_send_time}\r\n</p>\r\n<br />\r\n<div class=\"firebugResetStyles firebugBlockBackgroundColor\">\r\n	<div style=\"background-color:transparent ! important;\" class=\"firebugResetStyles\">\r\n	</div>\r\n</div>');");
E_D("replace into `ty_member_msg_tpl` values('consult_mall_reply','平台客服回复提醒','1','您的平台客服咨询已经回复。<a href=\"{\$consult_url}\" target=\"_blank\">点击查看回复</a>','0','【{\$site_name}】您的平台客服咨询已经回复。','0','{\$site_name}提醒：您的平台客服咨询已经回复。','<p>\r\n	{\$site_name}提醒：\r\n</p>\r\n<p>\r\n	您的平台客服咨询已经回复。\r\n</p>\r\n<p>\r\n	<a href=\"{\$consult_url}\" target=\"_blank\">点击查看回复</a> \r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$site_name}\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$mail_send_time}\r\n</p>');");
E_D("replace into `ty_member_msg_tpl` values('order_deliver_success','商品出库提醒','1','您的订单已经出库。<a href=\"{\$order_url}\" target=\"_blank\">点击查看订单</a>','0','【{\$site_name}】您的订单已经出库。订单编号 {\$order_sn}。','0','{\$site_name}提醒：您的订单已经出库。订单编号 {\$order_sn}。','<p>\r\n	{\$site_name}提醒：\r\n</p>\r\n<p>\r\n	您的订单已经出库。订单编号 {\$order_sn}。<br />\r\n<a href=\"{\$order_url}\" target=\"_blank\">点击查看订单</a>\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$site_name}\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$mail_send_time}\r\n</p>\r\n<br />');");
E_D("replace into `ty_member_msg_tpl` values('order_payment_success','付款成功提醒','1','关于订单：{\$order_sn}的款项已经收到，请留意出库通知。<a href=\"{\$order_url}\" target=\"_blank\">点击查看订单详情</a>','0','【{\$site_name}】{\$order_sn}的款项已经收到，请留意出库通知。','0','{\$site_name}提醒：{\$order_sn}的款项已经收到，请留意出库通知。','<p>\r\n	{\$site_name}提醒：\r\n</p>\r\n<p>\r\n	{\$order_sn}的款项已经收到，请留意出库通知。\r\n</p>\r\n<p>\r\n	<a href=\"{\$order_url}\" target=\"_blank\">点击查看订单详情</a>\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$site_name}\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$mail_send_time}\r\n</p>\r\n<br />');");
E_D("replace into `ty_member_msg_tpl` values('predeposit_change','余额变动提醒','1','你的账户于 {\$time} 账户资金有变化，描述：{\$desc}，可用金额变化 ：{\$av_amount}元，冻结金额变化：{\$freeze_amount}元。<a href=\"{\$pd_url}\" target=\"_blank\">点击查看余额</a>','0','【{\$site_name}】你的账户于 {\$time} 账户资金有变化，描述：{\$desc}，可用金额变化： {\$av_amount}元，冻结金额变化：{\$freeze_amount}元。','0','{\$site_name}提醒：你的账户于 {\$time} 账户资金有变化，描述：{\$desc}，可用金额变化： {\$av_amount}元，冻结金额变化：{\$freeze_amount}元。','<p>\r\n	{\$site_name}提醒：\r\n</p>\r\n<p>\r\n	你的账户于 {\$time} 账户资金有变化，描述：{\$desc}，可用金额变化：{\$av_amount}元，冻结金额变化：{\$freeze_amount}元。\r\n</p>\r\n<p>\r\n	<a href=\"{\$pd_url}\" target=\"_blank\">点击查看余额</a> \r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$site_name}\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$mail_send_time}\r\n</p>');");
E_D("replace into `ty_member_msg_tpl` values('recharge_card_balance_change','充值卡余额变动提醒','1','你的账户于 {\$time} 充值卡余额有变化，描述：{\$description}，可用充值卡余额变化 ：{\$available_amount}元，冻结充值卡余额变化：{\$freeze_amount}元。<a href=\"{\$url}\" target=\"_blank\">点击查看充值卡余额</a>','0','【{\$site_name}】你的账户于 {\$time} 充值卡余额有变化，描述：{\$description}，可用充值卡余额变化： {\$available_amount}元，冻结充值卡余额变化：{\$freeze_amount}元。','0','{\$site_name}提醒：你的账户于 {\$time} 充值卡余额有变化，描述：{\$description}，可用充值卡余额变化： {\$available_amount}元，冻结充值卡余额变化：{\$freeze_amount}元。','<p>\r\n    {\$site_name}提醒：\r\n</p>\r\n<p>\r\n  你的账户于 {\$time} 充值卡余额有变化，描述：{\$description}，可用充值卡余额变化：{\$available_amount}元，冻结充值卡余额变化：{\$freeze_amount}元。\r\n</p>\r\n<p>\r\n  <a href=\"{\$url}\" target=\"_blank\">点击查看余额</a> \r\n</p>\r\n<p>\r\n  <br />\r\n</p>\r\n<p>\r\n   <br />\r\n</p>\r\n<p>\r\n   <br />\r\n</p>\r\n<p style=\"text-align:right;\">\r\n {\$site_name}\r\n</p>\r\n<p style=\"text-align:right;\">\r\n   {\$mail_send_time}\r\n</p>');");
E_D("replace into `ty_member_msg_tpl` values('refund_return_notice','退款退货提醒','1','您的退款退货单有了变化。<a href=\"{\$refund_url}\" target=\"_blank\">点击查看</a>','0','【{\$site_name}】您的退款退货单有了变化。退款退货单编号：{\$refund_sn}。','0','{\$site_name}提醒：您的退款退货单有了变化。','<p>\r\n	{\$site_name}提醒：\r\n</p>\r\n<p>\r\n	您的退款退货单有了变化。退款退货单编号：{\$refund_sn}。\r\n</p>\r\n<p>\r\n	&lt;a href=\"{\$refund_url}\" target=\"_blank\"&gt;点击查看&lt;/a&gt;\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$site_name}\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$mail_send_time}\r\n</p>\r\n<br />');");
E_D("replace into `ty_member_msg_tpl` values('voucher_use','代金券使用提醒','1','您有代金券已经使用，代金券编号：{\$voucher_code}。<a href=\"{\$voucher_url}\" target=\"_blank\">点击查看</a>','0','【{\$site_name}】您有代金券已经使用，代金券编号：{\$voucher_code}。','0','{\$site_name}提醒：您有代金券已经使用，代金券编号：{\$voucher_code}。','<p>\r\n	{\$site_name}提醒：\r\n</p>\r\n<p>\r\n	您有代金券已经使用，代金券编号：{\$voucher_code}。\r\n</p>\r\n<p>\r\n	&lt;a href=\"{\$voucher_url}\" target=\"_blank\"&gt;点击查看&lt;/a&gt;\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$site_name}\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$mail_send_time}\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>');");
E_D("replace into `ty_member_msg_tpl` values('voucher_will_expire','代金券即将到期提醒','1','您有一个代金券即将在{\$indate}过期，请记得使用。<a href=\"{\$voucher_url}\" target=\"_blank\">点击查看</a>','0','【{\$site_name}】您有一个代金券即将在{\$indate}过期，请记得使用。','0','{\$site_name}提醒：您有一个代金券即将在{\$indate}过期，请记得使用。','<p>\r\n	{\$site_name}提醒：\r\n</p>\r\n<p>\r\n	您有一个代金券即将在{\$indate}过期，请记得使用。\r\n</p>\r\n<p>\r\n	<a href=\"{\$voucher_url}\" target=\"_blank\">点击查看</a> \r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$site_name}\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$mail_send_time}\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>');");
E_D("replace into `ty_member_msg_tpl` values('vr_code_will_expire','兑换码即将到期提醒','1','您有一组兑换码即将在{\$indate}过期，请记得使用。<a href=\"{\$vr_order_url}\" target=\"_blank\">点击查看</a>','0','【{\$site_name}】您有一组兑换码即将在{\$indate}过期，请记得使用。','0','{\$site_name}提醒：您有一组兑换码即将在{\$indate}过期，请记得使用。','<p>\r\n	{\$site_name}提醒：\r\n</p>\r\n<p>\r\n	您有一组兑换码即将在{\$indate}过期，请记得使用。\r\n</p>\r\n<p>\r\n	&lt;a href=\"{\$vr_order_url}\" target=\"_blank\"&gt;点击查看&lt;/a&gt;\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$site_name}\r\n</p>\r\n<p style=\"text-align:right;\">\r\n	{\$mail_send_time}\r\n</p>\r\n<p>\r\n	<br />\r\n</p>\r\n<p>\r\n	<br />\r\n</p>');");

require("../../inc/footer.php");
?>